
name: Building Uniblow binaries


on:
  push:
    tags: '*'
    branches: [ cicd, test_*]


jobs:

  build_mac:

    runs-on: macos-13-large

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Build bin package
      run: |
        ./package/Build-Mac.sh
    - name: 'Archive MacOS bin (unsigned!)'
      uses: actions/upload-artifact@v4
      with:
        name: macdist-unsigned
        path: |
          dist/
